# -*- coding: utf-8 -*-
"""Dictanory.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YEt01OlUoKU_FdnyUrmNXqVrftPFaBEB
"""

dict ={'apple': 'expensive','samsung': 150000,'pixel':100000}

dict['apple']

type(dict['apple'])

dict[apple]

"""input should be string"""

big = {'k1':123,'k2':[1,2,3],'k3':{'inside': 500}}

big['k1']

big["k3"]

big['k3']

big['k3'['inside']]

big['k3']['inside']

big['k3']= "hi barbie"

big

ha = big['k3']

type(ha)

clint = ha +" " + "wannna come"

print(clint)

big.keys()

big

big1 = {'k1': 123, 'k2': [1, 2, 3], 'k3': 'hi barbie'}

big == big1

big.items()

"""return is in form of tuples"""

