# -*- coding: utf-8 -*-
"""string.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mroUgXQhswV8AVEOkV_y-TAiqnX51kqM
"""

for x in range(6):
  print(x)

b="i am ankit"
print(len(a))

str="hey barbie wanna come"
if "oppenhiener" not in str:
  print("oppenhiener wins!!!!")

print(a[:])

print(a[3:])

print("Enter password that should be string!!1")
a = input()
if (a.lower() == "ankit"):
 print("Yeah your are absolutely correct !!!\n gREAT gUess ")
else:
 print("wrong guess!!")

b="    ygdyugud  yugdygn hdud"
print(b.strip())

c="kya haal hai bay"
print(c.replace("bay   ","pumaaa"))

#The split() method splits the string into substrings if it finds instances of the separator:

a = "Hello World!"
print(a.split("")) # returns ['Hello', ' World!']

txt = "welcome to the jungle"

x = txt.split()

print(x)

